# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
- develop

pr: none

variables:
  solution: 'OSDP-Bench.sln'
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  buildPlatform: 'x64|ARM64'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

jobs:
#- job: android_build
#  pool:
#    vmImage: 'windows-latest'
#  steps:
#    - template: ci/android-build.yml

#- job: winui_build
#  pool:
#    vmImage: 'windows-latest'
#  steps:
#    - template: ci/winui-build.yml
      
- job: testing
  pool:
    vmImage: 'windows-latest'
  steps:
    - template: ci/testing.yml