# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
- develop

pr: none

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

jobs:

- job: android-build
  pool:
    vmImage: 'windows-latest'
  steps:
    - template: ci/android-build.yml
      
- job: testing
  pool:
    vmImage: 'windows-latest'
  steps:
    - template: ci/testing.yml