steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '10.x'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: 'src/Core/Core.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build Core library'
    inputs:
      command: 'build'
      projects: 'src/Core/Core.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack Core library'
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/nuget'
      packagesToPack: 'src/Core/Core.csproj'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish NuGet package'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/nuget'
      artifactName: NuGet
